import jsPDF from "jspdf";

export type PdfRow = [string, string | undefined];

export function exportLookupPdf(opts: {
  title: string;
  subtitle?: string;
  reference?: string;
  photoBase64?: string; // no data: prefix
  fullName?: string;
  rows: PdfRow[];
  filename: string;
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 56;

  // Header band
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 80, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("LENS", 40, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(opts.title, 40, 58);
  doc.setFontSize(8);
  doc.text(new Date().toLocaleString(), W - 40, 40, { align: "right" });

  y = 110;
  doc.setTextColor(20, 20, 20);

  if (opts.photoBase64) {
    try {
      doc.addImage(`data:image/jpeg;base64,${opts.photoBase64}`, "JPEG", 40, y, 90, 110);
    } catch {
      /* ignore */
    }
  }

  const textX = opts.photoBase64 ? 150 : 40;
  if (opts.fullName) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(opts.fullName, textX, y + 20);
  }
  if (opts.reference) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90, 90, 90);
    doc.text(opts.reference, textX, y + 38);
  }
  if (opts.subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(opts.subtitle, textX, y + 54);
  }

  y += 140;
  doc.setDrawColor(220, 220, 220);
  doc.line(40, y, W - 40, y);
  y += 20;

  doc.setTextColor(20, 20, 20);
  const colW = (W - 80) / 2;
  const filled = opts.rows.filter(([, v]) => v);
  filled.forEach(([k, v], i) => {
    const col = i % 2;
    const x = 40 + col * colW;
    if (col === 0 && i > 0) y += 44;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(k.toUpperCase(), x, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(20, 20, 20);
    const lines = doc.splitTextToSize(String(v), colW - 12);
    doc.text(lines, x, y + 14);
    if (y > 760) {
      doc.addPage();
      y = 60;
    }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by LENS · Data via Dojah", 40, 820);

  doc.save(opts.filename);
}
