/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LogRouteImport } from './routes/log'
import { Route as LiveRouteImport } from './routes/live'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as IdentitiesRouteImport } from './routes/identities'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmlRouteImport } from './routes/aml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ApiPublicDojahDiagRouteImport } from './routes/api/public/dojah-diag'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesRoute = IdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlRoute = AmlRouteImport.update({
  id: '/aml',
  path: '/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDojahDiagRoute = ApiPublicDojahDiagRouteImport.update({
  id: '/api/public/dojah-diag',
  path: '/api/public/dojah-diag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aml': typeof AmlRoute
  '/auth': typeof AuthRoute
  '/cameras': typeof CamerasRoute
  '/enroll': typeof EnrollRoute
  '/identify': typeof IdentifyRoute
  '/identities': typeof IdentitiesRoute
  '/kyc': typeof KycRoute
  '/live': typeof LiveRoute
  '/log': typeof LogRoute
  '/network': typeof NetworkRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/api/public/dojah-diag': typeof ApiPublicDojahDiagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aml': typeof AmlRoute
  '/auth': typeof AuthRoute
  '/cameras': typeof CamerasRoute
  '/enroll': typeof EnrollRoute
  '/identify': typeof IdentifyRoute
  '/identities': typeof IdentitiesRoute
  '/kyc': typeof KycRoute
  '/live': typeof LiveRoute
  '/log': typeof LogRoute
  '/network': typeof NetworkRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/api/public/dojah-diag': typeof ApiPublicDojahDiagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aml': typeof AmlRoute
  '/auth': typeof AuthRoute
  '/cameras': typeof CamerasRoute
  '/enroll': typeof EnrollRoute
  '/identify': typeof IdentifyRoute
  '/identities': typeof IdentitiesRoute
  '/kyc': typeof KycRoute
  '/live': typeof LiveRoute
  '/log': typeof LogRoute
  '/network': typeof NetworkRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/api/public/dojah-diag': typeof ApiPublicDojahDiagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aml'
    | '/auth'
    | '/cameras'
    | '/enroll'
    | '/identify'
    | '/identities'
    | '/kyc'
    | '/live'
    | '/log'
    | '/network'
    | '/search'
    | '/settings'
    | '/profile/$id'
    | '/api/public/dojah-diag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aml'
    | '/auth'
    | '/cameras'
    | '/enroll'
    | '/identify'
    | '/identities'
    | '/kyc'
    | '/live'
    | '/log'
    | '/network'
    | '/search'
    | '/settings'
    | '/profile/$id'
    | '/api/public/dojah-diag'
  id:
    | '__root__'
    | '/'
    | '/aml'
    | '/auth'
    | '/cameras'
    | '/enroll'
    | '/identify'
    | '/identities'
    | '/kyc'
    | '/live'
    | '/log'
    | '/network'
    | '/search'
    | '/settings'
    | '/profile/$id'
    | '/api/public/dojah-diag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmlRoute: typeof AmlRoute
  AuthRoute: typeof AuthRoute
  CamerasRoute: typeof CamerasRoute
  EnrollRoute: typeof EnrollRoute
  IdentifyRoute: typeof IdentifyRoute
  IdentitiesRoute: typeof IdentitiesRoute
  KycRoute: typeof KycRoute
  LiveRoute: typeof LiveRoute
  LogRoute: typeof LogRoute
  NetworkRoute: typeof NetworkRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ApiPublicDojahDiagRoute: typeof ApiPublicDojahDiagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities': {
      id: '/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof IdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml': {
      id: '/aml'
      path: '/aml'
      fullPath: '/aml'
      preLoaderRoute: typeof AmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dojah-diag': {
      id: '/api/public/dojah-diag'
      path: '/api/public/dojah-diag'
      fullPath: '/api/public/dojah-diag'
      preLoaderRoute: typeof ApiPublicDojahDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmlRoute: AmlRoute,
  AuthRoute: AuthRoute,
  CamerasRoute: CamerasRoute,
  EnrollRoute: EnrollRoute,
  IdentifyRoute: IdentifyRoute,
  IdentitiesRoute: IdentitiesRoute,
  KycRoute: KycRoute,
  LiveRoute: LiveRoute,
  LogRoute: LogRoute,
  NetworkRoute: NetworkRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ProfileIdRoute: ProfileIdRoute,
  ApiPublicDojahDiagRoute: ApiPublicDojahDiagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
